/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesCreateIndexRouteImport } from './routes/stories/create/index'
import { Route as StoriesStoryIdIndexRouteImport } from './routes/stories/$storyId/index'
import { Route as StoriesCreateNewChapterRouteImport } from './routes/stories/create/new-chapter'
import { Route as StoriesStoryIdNewChapterRouteImport } from './routes/stories/$storyId/new-chapter'
import { Route as StoriesStoryIdEditRouteImport } from './routes/stories/$storyId/edit'
import { Route as StoriesStoryIdChaptersChapterIdEditRouteImport } from './routes/stories/$storyId/chapters/$chapterId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesCreateIndexRoute = StoriesCreateIndexRouteImport.update({
  id: '/stories/create/',
  path: '/stories/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdIndexRoute = StoriesStoryIdIndexRouteImport.update({
  id: '/stories/$storyId/',
  path: '/stories/$storyId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesCreateNewChapterRoute = StoriesCreateNewChapterRouteImport.update({
  id: '/stories/create/new-chapter',
  path: '/stories/create/new-chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdNewChapterRoute =
  StoriesStoryIdNewChapterRouteImport.update({
    id: '/stories/$storyId/new-chapter',
    path: '/stories/$storyId/new-chapter',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoriesStoryIdEditRoute = StoriesStoryIdEditRouteImport.update({
  id: '/stories/$storyId/edit',
  path: '/stories/$storyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdChaptersChapterIdEditRoute =
  StoriesStoryIdChaptersChapterIdEditRouteImport.update({
    id: '/stories/$storyId/chapters/$chapterId/edit',
    path: '/stories/$storyId/chapters/$chapterId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories': typeof StoriesIndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/new-chapter': typeof StoriesStoryIdNewChapterRoute
  '/stories/create/new-chapter': typeof StoriesCreateNewChapterRoute
  '/stories/$storyId': typeof StoriesStoryIdIndexRoute
  '/stories/create': typeof StoriesCreateIndexRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories': typeof StoriesIndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/new-chapter': typeof StoriesStoryIdNewChapterRoute
  '/stories/create/new-chapter': typeof StoriesCreateNewChapterRoute
  '/stories/$storyId': typeof StoriesStoryIdIndexRoute
  '/stories/create': typeof StoriesCreateIndexRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/stories/$storyId/edit': typeof StoriesStoryIdEditRoute
  '/stories/$storyId/new-chapter': typeof StoriesStoryIdNewChapterRoute
  '/stories/create/new-chapter': typeof StoriesCreateNewChapterRoute
  '/stories/$storyId/': typeof StoriesStoryIdIndexRoute
  '/stories/create/': typeof StoriesCreateIndexRoute
  '/stories/$storyId/chapters/$chapterId/edit': typeof StoriesStoryIdChaptersChapterIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/new-chapter'
    | '/stories/create/new-chapter'
    | '/stories/$storyId'
    | '/stories/create'
    | '/stories/$storyId/chapters/$chapterId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stories'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/new-chapter'
    | '/stories/create/new-chapter'
    | '/stories/$storyId'
    | '/stories/create'
    | '/stories/$storyId/chapters/$chapterId/edit'
  id:
    | '__root__'
    | '/'
    | '/stories/'
    | '/stories/$storyId/edit'
    | '/stories/$storyId/new-chapter'
    | '/stories/create/new-chapter'
    | '/stories/$storyId/'
    | '/stories/create/'
    | '/stories/$storyId/chapters/$chapterId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  StoriesStoryIdEditRoute: typeof StoriesStoryIdEditRoute
  StoriesStoryIdNewChapterRoute: typeof StoriesStoryIdNewChapterRoute
  StoriesCreateNewChapterRoute: typeof StoriesCreateNewChapterRoute
  StoriesStoryIdIndexRoute: typeof StoriesStoryIdIndexRoute
  StoriesCreateIndexRoute: typeof StoriesCreateIndexRoute
  StoriesStoryIdChaptersChapterIdEditRoute: typeof StoriesStoryIdChaptersChapterIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/create/': {
      id: '/stories/create/'
      path: '/stories/create'
      fullPath: '/stories/create'
      preLoaderRoute: typeof StoriesCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/': {
      id: '/stories/$storyId/'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/create/new-chapter': {
      id: '/stories/create/new-chapter'
      path: '/stories/create/new-chapter'
      fullPath: '/stories/create/new-chapter'
      preLoaderRoute: typeof StoriesCreateNewChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/new-chapter': {
      id: '/stories/$storyId/new-chapter'
      path: '/stories/$storyId/new-chapter'
      fullPath: '/stories/$storyId/new-chapter'
      preLoaderRoute: typeof StoriesStoryIdNewChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/edit': {
      id: '/stories/$storyId/edit'
      path: '/stories/$storyId/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof StoriesStoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/chapters/$chapterId/edit': {
      id: '/stories/$storyId/chapters/$chapterId/edit'
      path: '/stories/$storyId/chapters/$chapterId/edit'
      fullPath: '/stories/$storyId/chapters/$chapterId/edit'
      preLoaderRoute: typeof StoriesStoryIdChaptersChapterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  StoriesStoryIdEditRoute: StoriesStoryIdEditRoute,
  StoriesStoryIdNewChapterRoute: StoriesStoryIdNewChapterRoute,
  StoriesCreateNewChapterRoute: StoriesCreateNewChapterRoute,
  StoriesStoryIdIndexRoute: StoriesStoryIdIndexRoute,
  StoriesCreateIndexRoute: StoriesCreateIndexRoute,
  StoriesStoryIdChaptersChapterIdEditRoute:
    StoriesStoryIdChaptersChapterIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
